export const typography = {
  h1: {
    fontFamily: 'Urbanist',
    fontWeight: 700,
    fontSize: '35px',
    lineHeight: '100%',
    letterSpacing: '0%',
    verticalAlign: 'middle',
    color: '#ffffff',
  },
  h2: {
    fontFamily: 'Urbanist',
    fontWeight: 700,
    fontSize: '35px',
    lineHeight: '100%',
    letterSpacing: '0%',
    verticalAlign: 'middle',
    color: '#00E7F9',
  },
  body: {
    fontFamily: 'Figtree',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '22px',
    letterSpacing: '0%',
    verticalAlign: 'middle',
  },
  small: {
    fontFamily: 'Figtree',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0%',
    textAlign: 'center' as const,
    verticalAlign: 'middle',
  },
  footer: {
    fontFamily: 'Figtree',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '100%',
    letterSpacing: '0%',
    verticalAlign: 'middle',
  },
}; 